### PR TITLE
Disable Scala.js' `linker` project.

### PR DESCRIPTION
**Pull request by sjrd**
It requires the parallel collections, which are not yet available for 2.13.x.

This should allow scala-js to successfully complete, now. We've updated Scala.js' `master` to work with the latest 2.13.x nightly.

### CODE REVIEW

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1687/

**Comment by sjrd** [comment]
Hum there's still this thing:
```
[scala-js] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.16/project-builds/scala-js-9a9690b835581985028966038686ddede973d10b/scalalib/overrides-2.13/scala/reflect/Manifest.scala:48: error: Manifest is already defined as value Manifest in package object reflect
[scala-js] [error] trait Manifest[T] extends ClassManifest[T] with Equals {
[scala-js] [error]       ^
[scala-js] [info] one error found
```
I need to investigate it more, but I suggest we merge this PR anyway, because further fixes should be in scala/scala or in scala-js/scala-js, not here.
