### PR TITLE
2.13: new Scala SHA

### PR DESCRIPTION
**Pull request by SethTisue**
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1545/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1546/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1553/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1554/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1555/~~
~~https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1556/~~
https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1558/

### CODE REVIEW

**Comment by SethTisue** [comment]
gah

https://scala-ci.typesafe.com/job/scala-2.13.x-jdk11-integrate-community-build/1545/artifact/logs/akka-stream-build.log

```
[akka-stream] [error] /home/jenkins/workspace/scala-2.13.x-jdk11-integrate-community-build/target-0.9.16/project-builds/akka-stream-ac13d37ddedac945c1f3752ed21602e993de9f2d/akka-stream/src/main/scala/akka/stream/impl/ResizableMultiReaderRingBuffer.scala:9:8: illegal cyclic reference involving object ResizableMultiReaderRingBuffer
[akka-stream] [error] import ResizableMultiReaderRingBuffer._
[akka-stream] [error]        ^
```

**Comment by SethTisue** [comment]
reproducible outside dbuild with some trouble

in the silencer repo you `git checkout v1.6.0`, `sbt`, `++2.13.3-bin-db119f9`, `set every version := "1.6.0"`, `publishLocal`

then in akka repo

```diff
diff --git project/AkkaDisciplinePlugin.scala project/AkkaDisciplinePlugin.scala
index 0c42b3a8d7..eedd85b16d 100644
--- project/AkkaDisciplinePlugin.scala
+++ project/AkkaDisciplinePlugin.scala
@@ -47,8 +47,8 @@ object AkkaDisciplinePlugin extends AutoPlugin {
     val silencerVersion = "1.6.0"
     Seq(
       libraryDependencies ++= Seq(
-          compilerPlugin(("com.github.ghik" %% "silencer-plugin" % silencerVersion).cross(CrossVersion.patch)),
-          ("com.github.ghik" %% "silencer-lib" % silencerVersion % Provided).cross(CrossVersion.patch)))
+          compilerPlugin(("com.github.ghik" %% "silencer-plugin" % silencerVersion).cross(CrossVersion.full)),
+          ("com.github.ghik" %% "silencer-lib" % silencerVersion % Provided).cross(CrossVersion.full)))
```

then `sbt -J-Dakka.no.discipline=true`, `++2.13.3-bin-db119f9`, `akka-stream/compile`

you can work around it with:

```diff
--- a/akka-stream/src/main/scala/akka/stream/impl/ResizableMultiReaderRingBuffer.scala
+++ b/akka-stream/src/main/scala/akka/stream/impl/ResizableMultiReaderRingBuffer.scala
@@ -7,8 +7,6 @@ package akka.stream.impl
 import scala.annotation.tailrec
 import scala.util.control.NoStackTrace
 
-import ResizableMultiReaderRingBuffer._
-
 import akka.annotation.InternalApi
 
 /**
@@ -20,7 +18,9 @@ import akka.annotation.InternalApi
 @InternalApi private[akka] class ResizableMultiReaderRingBuffer[T](
     initialSize: Int, // constructor param, not field
     maxSize: Int, // constructor param, not field
-    val cursors: Cursors) {
+    val cursors: ResizableMultiReaderRingBuffer.Cursors) {
+  import ResizableMultiReaderRingBuffer._
+
```

next step: think about whether this is a regression

**Comment by SethTisue** [comment]
curiouser and curiouser: the compilation error goes away if you remove the `@InternalApi` annotation from `object ResizableMultiReaderRingBuffer`

but it doesn't have to be that annotation in particular. adding `@nowarn` or `@strictfp` also does it

LOL, it boils down to just:

```
import S._
@annotation.strictfp object S
```

`git bisect` says https://github.com/scala/scala/pull/9023 is where this regressed; I'll comment in more detail there

**Comment by SethTisue** [comment]
LOL, it boils down to just:

```
import S._
@annotation.strictfp object S
```

**Comment by SethTisue** [comment]
`git bisect` says https://github.com/scala/scala/pull/9023 is where this regressed; I'll comment there

**Comment by SethTisue** [comment]
another file was hit, `akka-stream/src/main/scala-jdk-9/akka/stream/impl/JavaFlowAndRsConverters.scala` needed https://github.com/scalacommunitybuild/akka/commit/c5b86ce1159baf4082acd4a26275b47fcf9b8f5c

the details are a little different — the import was a `import Foo.Implicits._`, but it worked to just move the import until after `object Foo ...`.

**Comment by SethTisue** [comment]
it seems scala/scala#9023 will be reverted, but for now I worked around it; I'll remove the workarounds in the next round
